ToyMC: icarus_toymc_extended
Detector: icarus_detector
photonlib:
  filepath: plib_icarus.h5

data:
  dataset:
    filepath: /sdf/home/y/youngsam/data/soptim_dataset_50k_uniform.h5
    size: 20000
  loader:
    batch_size: 200
    drop_last: true
    num_workers: 4
    pin_memory: true
    shuffle: true
  weight: 1.0

device:
  type: cuda

logger:
  analysis:
    abs_bias:
    rel_bias:
  dir_name: logs_soptim
  file_name: log.csv
  log_every_nsteps: 25

model:
  ckpt_file: 
  network:
    hidden_features: 512
    hidden_layers: 5
    in_features: 3
    out_features: 180
  output_scale:
    fix: true

train:
  optimizer_class: Adam
  optimizer_param:
    lr: 5.0e-05
  lr_scheduler:
    name: ReduceLROnPlateau
    parameters:
      factor: 0.9
      mode: min
      patience: 10
      threshold: 0.1
      threshold_mode: rel
    validation_split: 0.1
  max_epochs: 1000
  optimizer_class: Adam
  resume: false
  save_every_epochs: 25

transform_vis:
  eps: 1.0e-07
  sin_out: true
  vmax: 1.0
